### ISSUE TITLE
编译的时候的错误

### ISSUE THREAD

**Issue by semazengyi** [CatchChat/Yep#10]
![image](https://cloud.githubusercontent.com/assets/3383471/12739303/5b6faad6-c9a3-11e5-85bd-f4ce27d0c86d.png)

Yep-develop/Yep/Services/FayeService.swift:84:39: Missing argument for parameter 'success' in call

**Comment by kevinzhow** [comment]
你的 Xcode 版本是 7.2 吗?

**Comment by semazengyi** [comment]
对

**Comment by Cee** [comment]
是在 develop 分支吗？

**Comment by semazengyi** [comment]
恩恩，是dev分支
