### ISSUE TITLE
关于服务端的疑问

### ISSUE THREAD

**Issue by davidear** [CatchChat/Yep#105]
非常感谢作者的分享精神，真的特别棒。
能够分享客户端已经是非常不容易的事，不奢求任何其他，只是求证一下。
我在跑模拟器的时候，貌似后台接口已经改动了还是怎样，已经不能正常运行了。
问题1，请问是不是服务端做了变化，不会支持开源的这个版本的网络请求了？
问题2，请问是所有的请求都不支持了，还是仅仅某个模块的请求不支持了，如登录注册？

**Comment by kevinzhow** [comment]
为了避免太多模拟器用户进入生产环境，所以我们注释掉了相关 URL
