### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by lwoodenheart** [CatchChat/Yep#125]
下载后，pod install，出现 /usr/bin/curl -f -L -o /var/folders/z7/grjc4h9n7b535nfwlljq55lh0000gn/T/d20160504-1038-aiqyut/file.zip http://www.appsee.com/sdk/appsee_ios_2.2.zip --create-dirs

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by kevinzhow** [comment]
Xcode 7.3.1 的问题，升级到 cocoapods 1.0.0 rc2
