### ISSUE TITLE
Error installing Appsee

### ISSUE THREAD

**Issue by Rayzworld** [CatchChat/Yep#13]
[!] Error installing Appsee
[!] /usr/bin/curl -f -L -o /var/folders/7d/jky3kjhx20z4c4h33x7ts_1w0000gn/T/d20160202-63845-1e47b9h/file.zip http://www.appsee.com/sdk/appsee_ios_2.1.5.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170  100   170    0     0     39      0  0:00:04  0:00:04 --:--:--    40
  0 3718k    0 15651    0     0     50      0 21:09:22  0:05:08 21:04:14     0curl: (56) SSLRead() return error -9806

找了这个http://stackoverflow.com/questions/30385939/git-clone-fails-with-sslread-error-on-os-x-yosemite 没解决

**Comment by Cee** [comment]
给一下你的 CocoaPods 版本，报错完整信息。
尝试重新从最新的 dev 分支编译。

**Comment by qy1010** [comment]
报错完整信息：
[!] Error installing Appsee
[!] /usr/local/anaconda3/bin/curl -f -L -o /var/folders/57/44vy66d96l74np69k8w2kdt80000gn/T/d20210609-47290-1f5atyt/file.zip https://www.appsee.com/sdk/appsee_ios_2.6.2.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 1 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 2 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: www.appsee.com

--------------

CocoaPods ： 1.9.0
