### ISSUE TITLE
'APService.h' file not found

### ISSUE THREAD

**Issue by Evoque** [CatchChat/Yep#14]
![image](https://cloud.githubusercontent.com/assets/3809046/12739824/09a1871a-c9a8-11e5-85ae-2c61b577f5b7.png)

**Comment by Evoque** [comment]
已经用最新的cocoapod编译了。 @kevinzhow

**Comment by Cee** [comment]
Checkout the latest `develop` or `master` branch.

**Comment by Evoque** [comment]
OK let me try @Cee

**Comment by Evoque** [comment]
![image](https://cloud.githubusercontent.com/assets/3809046/12740062/97c53170-c9aa-11e5-85d4-b1edf04c6e60.png)
@Cee   
![image](https://cloud.githubusercontent.com/assets/3809046/12740069/a24cf830-c9aa-11e5-9114-191e8dc4d03a.png)

**Comment by BichengLUO** [comment]
The same issue with the up-to-date `master` branch.

'APService.h' not found

**Comment by j364960953** [comment]
楼上的兄弟，解决了吗？这个app好难安装呀
(*^__^*) 嘻嘻……

**Comment by Evoque** [comment]
成功了， 自己把代码改了， 估计以后会有bug

**Comment by Evoque** [comment]
还要改linker。

**Comment by nixzhu** [comment]
在 develop 分支升级了 pods，修正了 Kingfisher 2.0 的兼容。

如果编译提示 weak library 与 bitcode 字样，请在项目内搜索 `-weak_library /usr/lib/libz.dylib`，将对应 link 参数删除即可，这似乎是由 JPush 引入的。

**Comment by j364960953** [comment]
怎么改的？？

**Comment by j364960953** [comment]
@Evoque

**Comment by woshicainiaoma** [comment]
@Evoque Checkout the latest develop or master branch.    这句意思我看懂了，能告诉我是怎么操作的吗，谢谢了
