### ISSUE TITLE
Thx周大大

### ISSUE THREAD

**Issue by ThinkWYP** [CatchChat/Yep#15]
非常感谢，开源的魄力让我震惊，已经成功运行，虽然现在刚开始学Swift，OC一点不懂，能Run起来非常开心，会从这个Project中学到不少东西的，我感觉

**Comment by Evoque** [comment]
你成功了？ 迁出之后，只cocoapods编译就行？

**Comment by ThinkWYP** [comment]
clone 之后，切换到develop分支，然后pod  install一下，打开Yep.xcworkspace就好了

**Comment by semazengyi** [comment]
一样的操作，No such module 'MZFayeClient'，我也是醉了

**Comment by ThinkWYP** [comment]
@semazengyi 你肯定不是最新的代码，或者肯定不是develo分支，因为最新的develop分支已经注释了这个

**Comment by quietStefan** [comment]
fork后，下载了develo分支，报错【index_set.hpp file not found】.

**Comment by quietStefan** [comment]
我是在模拟器上跑的

**Comment by mshhmzh** [comment]
pod file 里 MZFayeClient 被注释了。。。。

**Comment by quietStefan** [comment]
@mshhmzh  应该怎么改？

**Comment by semazengyi** [comment]
@quietStefan  照题主说的弄，我好了，记得切换dev

**Comment by quietStefan** [comment]
@semazengyi 我再试试，

**Comment by quietStefan** [comment]
@semazengyi  【#include "index_set.hpp" file not found】。我也是fork后，切到develop分支，下载，pod install。运行，但是就是报错

**Comment by ThinkWYP** [comment]
@quietStefan 你的Xcode是最新的吗

**Comment by quietStefan** [comment]
@ThinkWYP  Xcode Version 7.1.1 (7B1005)

**Comment by ThinkWYP** [comment]
@quietStefan 我们是7.2，请使用最新的再一试

**Comment by quietStefan** [comment]
@ThinkWYP  OK。

**Comment by j364960953** [comment]
fatal error: unexpectedly found nil while unwrapping an Optional value

真机运行错

误。模拟器可以跑

**Comment by sauchye** [comment]
按照题主操作 依然提示缺少``MZFayeClient``

**Comment by Airsola** [comment]
已切换到 Develop 分支，但是还是不行... 还是 #import "APService.h" 文件不存在...跑不起来真纠结，又那个fork是已经跑起来的，想换个试试

**Comment by kevinzhow** [comment]
@Airsola 记得 Pull 最新代码
