### ISSUE TITLE
Downloading core failed.

### ISSUE THREAD

**Issue by WilliamCheen** [CatchChat/Yep#18]
执行Pod install 后，Installing Realm 出问题了

.......
Installing Realm (0.97.0)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.95.5
Downloading core failed. Please try again once you have an Internet connection.

**Comment by nixzhu** [comment]
1. 用 pod update
2. Realm 的库比较大，可能也需要有稳定的网络或VPN
