### ISSUE TITLE
使用pod install报错

### ISSUE THREAD

**Issue by zhangli4659507** [CatchChat/Yep#191]
Invalid `Podfile` file: undefined method `inherit!' for #Pod::Podfile:0x007fe10206def8. Updating CocoaPods might fix the issue.

**Comment by marcohinen** [comment]
- Open terminal 
- Type the command ( $ sudo gem install cocoapods ) That will update your CoccaPods
- Then, try installing the pod again.

Hope that helps 👍

**Comment by zhangli4659507** [comment]
i haved install cocoapods
