### ISSUE TITLE
all above "pod" file are dismiss

### ISSUE THREAD

**Issue by LittleLittleStar** [CatchChat/Yep#22]
after download,the project can't run! All above "pod" file are dismiss.No matter pod install or pod update,still not working

**Comment by kevinzhow** [comment]
are you using Yep.xcworkspace?

**Comment by qrh168** [comment]
yes,i used,but error still: 
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by Cee** [comment]
Have you run `pod install`?

**Comment by qrh168** [comment]
of course
Cocoapods（version 0.39.0）and  Xcode 7.2

**Comment by Cee** [comment]
@qrh168 It's strange.
Maybe you can `rm -rf Yep.xcworkspace` then run `pod install`.

**Comment by gongjujun** [comment]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
![image](https://cloud.githubusercontent.com/assets/12054470/12802803/66dcdd7a-cb20-11e5-9ea7-34be18d57695.png)

**Comment by Cee** [comment]
@gongjujun try `gem uninstall cocoapods && gem install cocoapods` (maybe add `sudo` before).

**Comment by gongjujun** [comment]
试了下,还是不行......
![image](https://cloud.githubusercontent.com/assets/12054470/12804591/74fbdb36-cb2f-11e5-8d21-ed852a60aa63.png)

**Comment by kevinzhow** [comment]
下载 Realm 失败……得换个网好的地方并采用科学上网

**Comment by tardyRain** [comment]
@gongjujun      yes I have the same problem, and I run     rm -rf Yep.xcworkspace  then run   pod install   , the error is dismiss. But met another error. 

realm/util/features.h file not found

**Comment by wealon** [comment]
my error info is: 
~/Yep/Pods/Realm/Realm/ObjectStore/index_set.cpp:19:10: 'index_set.hpp' file not found

**Comment by wealon** [comment]
➜  Yep git:(develop) pod install 
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using 1PasswordExtension (1.7)
Using APAddressBook (0.2.3)
Using Alamofire (3.1.5)
Using Appsee (2.1.5)
Using Base64 (1.0.1)
Using Crashlytics (3.6.0)
Using DeviceGuru (1.3.3)
Using FXBlurView (1.6.4)
Using Fabric (1.6.4)
Using JPush-iOS-SDK (1.8.8)
Using Kanna (1.0.4)
Using KeyboardMan (0.5.2)
Using Kingfisher (2.0.1)
Using MonkeyKing (0.0.2)
Using Navi (0.3.9)
Using Proposer (0.7.1)
Using Realm (0.97.1)
Using RealmSwift (0.97.1)
Using Ruler (0.6)
Using SocketRocket (0.4.2)
Using TPKeyboardAvoiding (1.2.11)
Using pop (1.0.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 21 dependencies from the Podfile and 22 total pods installed.
➜  Yep git:(develop)

**Comment by wealon** [comment]
➜  Yep git:(develop) pod --version
0.39.0

**Comment by wealon** [comment]
xcode version is           Version 7.2 (7C68)

**Comment by wealon** [comment]
error:~/Yep/Pods/RealmSwift/RealmSwift/Aliases.swift:20:8: No such module 'Realm'

**Comment by wealon** [comment]
what's wrong  with my problem

**Comment by wealon** [comment]
3Q

**Comment by lidaren** [comment]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Help~

**Comment by 03128crz** [comment]
@gongjujun podfile注释掉RealmSwift,从官网手动下载zip包安装

**Comment by renyufei8023** [comment]
我靠 公司100兆光纤  开了vpn也没有把Realm下载下来，在家里面移动光纤几分钟解决问题，赶紧运行一下去
