### ISSUE TITLE
English Readme

### ISSUE THREAD

**Issue by gmertk** [CatchChat/Yep#25]
Hi,

With all my respect and appreciation, is it possible you can translate the readme to English?

Cheers!

**Comment by Cee** [comment]
Sure!
Update soon!

**Comment by ppamorim** [comment]
+1

**Comment by Cee** [comment]
@gmertk @ppamorim I've just wrote a simple English guide. :)

**Comment by gmertk** [comment]
Thank you @Cee!

**Comment by Cee** [comment]
If you have any questions, do not be nervous to ask!
