### ISSUE TITLE
 index_set.hpp file not found 

### ISSUE THREAD

**Issue by huangjianke** [CatchChat/Yep#26]
help!!!

**Comment by YueJun1991** [comment]
+1
cocoapods version 0.39.0
Realm (0.97.1)
RealmSwift (0.97.1)

**Comment by fanbin0602** [comment]
+1

**Comment by iStig** [comment]
+1

![Uploading 72AA9888-0FE0-4868-B935-46B1DE91FF62.png…]()
![Uploading BD9F777E-7C1B-4E0D-BF44-9C3BDEAD8ED7.png…]()

**Comment by iStig** [comment]
i had fix this issue follow this link 
http://stackoverflow.com/questions/35013165/realmswift-getting-realm-util-features-h-not-found-when-compiling

**Comment by YueJun1991** [comment]
Thx! @iStig 
Success!

**Comment by huangjianke** [comment]
Thx! @iStig 
Success!

**Comment by ZwxWhite** [comment]
working
THX
