### ISSUE TITLE
No such module 'MZFayeClient'

### ISSUE THREAD

**Issue by lycaste** [CatchChat/Yep#3]
pod 安装之后运行报错...

**Comment by coolzilj** [comment]
我也遇到了同样错误，参考了SO这个回答后，http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift ，里面说
> No need to import explicitly, that's what the bridging header is for.
经测试，只要把 https://github.com/CatchChat/Yep/blob/master/Yep/Services/FayeService.swift#L10
注释掉就可以顺利运行了，至少 work for me

**Comment by Airsola** [comment]
「经测试，只要把 https://github.com/CatchChat/Yep/blob/master/Yep/Services/FayeService.swift#L10
注释掉就可以顺利运行了，至少 work for me」
我已经注释掉这行了，但是依然不行...不明求解
![image](https://cloud.githubusercontent.com/assets/5841061/12738640/831f1892-c99d-11e5-9d1b-b8591851bf05.png)

**Comment by coolzilj** [comment]
@Airsola 你这是另一个错误，参考 https://github.com/CatchChat/Yep/pull/5/commits 
因为PR被拒了，你可以着急跑起来先试下我 fork 的 repo https://github.com/coolzilj/Yep

**Comment by kevinzhow** [comment]
最新的 Develop 分支应该是没问题了

**Comment by coolzilj** [comment]
@kevinzhow 测试了最新的 develop 分支还是有 MZFayeClient 的错误
