### ISSUE TITLE
imageCache 文件错误

### ISSUE THREAD

**Issue by lyimin** [CatchChat/Yep#32]
![f415b92b-cf97-41b7-b467-0db59fc748b8](https://cloud.githubusercontent.com/assets/7721713/12772615/d4964f76-ca6d-11e5-8632-ce9c4573e8f8.png)

**Comment by lyimin** [comment]
Kingfisher 版本是2.0.1

**Comment by lyimin** [comment]
![3a138043-6d0b-4e60-9665-84be9ab0face](https://cloud.githubusercontent.com/assets/7721713/12772643/22f4f47e-ca6e-11e5-9245-fa899326c35c.png)
求大大们看看。

**Comment by Cee** [comment]
Try `pod install --no-repo-update`.

**Comment by lyimin** [comment]
还是编译不过！！

**Comment by kevinzhow** [comment]
试试最新的 Develop 分支代码 @lyimin

**Comment by lyimin** [comment]
屌屌屌。谢谢周总
