### ISSUE TITLE
Failed to code sign "Yep".

### ISSUE THREAD

**Issue by linwkr** [CatchChat/Yep#33]
终端提示，当前是develop分支
git branch -v
*develop 96c111c alertCanNotAccessCameraRoll for check failed of UIImagePickerController.isSourceTypeAvailable(.PhotoLibrary)
master  5345257 [Close #25] Translate Readme into English

Xcode提示：
Failed to code sign "Yep".

None of the valid provisioning profiles allowed the specified entitlements: com.apple.developer.associated-domains, com.apple.security.application-groups.

**Comment by Cee** [comment]
See #24
