### ISSUE TITLE
SRWebSocket.h file not found

### ISSUE THREAD

**Issue by orzcc** [CatchChat/Yep#34]
最新的 develop 分支的代码也一样，出现这个错误，不知道何解？

`/xxx/Yep/Yep/Yep-Bridging-Header.h:7:9: note: in file included from /xxx/Yep/Yep/Yep-Bridging-Header.h:7:
#import "MZFayeClient.h"

/xxx/Yep/Yep/Vendors/MZFayeClient/MZFayeClient.h:27:9: error: 'SocketRocket/SRWebSocket.h' file not found
#import <SocketRocket/SRWebSocket.h>

<unknown>:0: error: failed to import bridging header '/xxx/Yep/Yep/Yep-Bridging-Header.h'`

**Comment by Cee** [comment]
`pod install` first.

**Comment by orzcc** [comment]
`Sending stats
Pod installation complete! There are 21 dependencies from the Podfile and 22
total pods installed.`

已经安装好了的。

**Comment by orzcc** [comment]
不好意思，忘记用 .xcworkspace打开了
