### ISSUE TITLE
Mobile number can't receive verification code in Taiwan

### ISSUE THREAD

**Issue by YueJun1991** [CatchChat/Yep#35]
: ) I can't sign up.
Only use China number?

**Comment by kevinzhow** [comment]
@tumayun Please check this

**Comment by YueJun1991** [comment]
😂ok I received it just used 30 mins : )

**Comment by Cee** [comment]
@YueJun1991 Too slow😂

**Comment by tumayun** [comment]
@YueJun1991 Already logged in yet?

**Comment by YueJun1991** [comment]
@tumayun yeah!
Just more patient and attentive.

**Comment by YueJun1991** [comment]
@Cee Not too slow....maybe....

**Comment by tboneticklez** [comment]
Fork
