### ISSUE TITLE
No such module 'MZFayeClient'

### ISSUE THREAD

**Issue by red010182** [CatchChat/Yep#39]
I've just downloaded this project then pod install. I didn't do anything but just build and run, however, it shows an error:

In FayeService.swift: `import MZFayeClient` cannot find moudle `MZFayeClient`. 
MZFayeClient is actually added to project under the folder Vendor, and `Yep-Bridging-Header.h` is set correctly.

In project setting, Objective-C Bridging Header is set to `Yep/Yep-Bridging-Header.h` which I think is correct. 

Yep-Bridging-Header.h

```
#import <UIKit/UIKit.h>
#import "JPUSHService.h"
#import "MZFayeClient.h"
```

Everything seems fine but just can't build. The compiler cannot find `MZFayeClient`, any solution?

Thanks.

**Comment by red010182** [comment]
I've also noticed that in Podfile this line `#    pod 'MZFayeClient', :path => '../CatchLib-iOS/MZFayeClient/'`is commented out, does there any reason import MZFayeClient manually? Is it need to be customised?

**Comment by Cee** [comment]
@red010182 Have you pulled the latest code?

**Comment by zhaodazhou** [comment]
@red010182 I have the same problem. Do you solution?

**Comment by red010182** [comment]
Yes, git clone the latest version fixed the problem.
zhaodazhou <notifications@github.com>於 2016年2月3日 週三，下午9:56寫道：
