### ISSUE TITLE
提示  APService.h  没找到

### ISSUE THREAD

**Issue by ucoker** [CatchChat/Yep#4]
提示  APService.h  没找到

已更新如下依赖

Using 1PasswordExtension (1.7)
Using APAddressBook (0.2.3)
Using Alamofire (3.1.5)
Using Base64 (1.0.1)
Using Crashlytics (3.6.0)
Using DeviceGuru (1.3.3)
Using FXBlurView (1.6.4)
Using Fabric (1.6.4)
Using JPush-iOS-SDK (2.1.0)
Using Kanna (1.0.3)
Using KeyboardMan (0.5.2)
Using Kingfisher (2.0.0)
Using MonkeyKing (0.0.2)
Using Navi (0.3.9)
Using Proposer (0.7.1)
Using Realm (0.97.0)
Using RealmSwift (0.97.0)
Using Ruler (0.6)
Using SocketRocket (0.4.2)
Using TPKeyboardAvoiding (1.2.11)
Using pop (1.0.8)

**Comment by tangqi92** [comment]
pod install 后出现
![img_0305](https://cloud.githubusercontent.com/assets/10348598/12725712/f6eb03fc-c94e-11e5-8779-d8b2f87de769.JPG)

**Comment by ucoker** [comment]
我刚尝试 pod install ，仍然一样的错误。
![qq20160202-0](https://cloud.githubusercontent.com/assets/12216739/12726652/b646d8b2-c953-11e5-9a19-07d0045f55f2.png)

**Comment by tangqi92** [comment]
是的，我也是这个错误，我只是贴个图表示我 pod install 了，而不是说我解决了，你可能误会了。

**Comment by ucoker** [comment]
误会，不知如何解决？

**Comment by coolzilj** [comment]
我是已经成功跑起来的，看了下 APService.h 是在这个 pod 'JPush-iOS-SDK' 里的，
我 pod install 安装的是
Installing JPush-iOS-SDK (1.8.8)
也许是版本的问题，
于是，我找了一下 JPush-iOS-SDK 的 github repo, 
https://github.com/iosmvn/JPush-iOS-SDK/commit/dd8a6e05d8603d18d7efe107d29b23e5eb212e9a
发现，APService 改成了 JPUSHService，
https://github.com/iosmvn/JPush-iOS-SDK/commit/dd8a6e05d8603d18d7efe107d29b23e5eb212e9a#diff-66ef969dcb1e660084ef75f6c7671b8bR15
你们可以试试

**Comment by ucoker** [comment]
好的。我稍后尝试看看 谢谢

**Comment by Cee** [comment]
Try `pod _0.39.0_ install` if you're using 1.0.0.beta.2.

**Comment by Airsola** [comment]
已经把 https://github.com/CatchChat/Yep/blob/master/Yep/Yep-Bridging-Header.h#L6 改成 
#import "JPUSHService.h"以及代码里的 APService 改成 JPUSHService。
但是接下来就报 No such module 'MZFayeClient' ... 问题依旧存在

**Comment by njovy** [comment]
@coolzilj Thank you. I was able to run on my device using your repo!

**Comment by kevinzhow** [comment]
Develop 分支已修复
