### ISSUE TITLE
Support CocoaPods 1.0?

### ISSUE THREAD

**Issue by honghaoz** [CatchChat/Yep#43]
I got this error: 
![screen shot 2016-02-03 at 1 43 05 pm](https://cloud.githubusercontent.com/assets/3926785/12792940/199d816c-ca7c-11e5-9817-8e4c17144ade.png)

In `develop` branch, pulled last code.

I'm using `CocoaPods 1.0.0.beta.2`.

**Comment by Cee** [comment]
Realm will not work if you are using 1.0.0.beta.2
Try `pod _0.39.0_ install`.

**Comment by honghaoz** [comment]
awesome! it works, thanks!
