### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by sushiwu** [CatchChat/Yep#430]
现在怎么编译不通过了

**Comment by Arcovv** [comment]
@returnight 
Carthage update的時候，記得Alamofire的版本。
我把Podfile文件幾乎都改過了。
現在至少模擬器上就完全能跑了。

**Comment by GitZhouQi** [comment]
编译成功了吗现在，我这边Carthage里面好多文件都没加上去

**Comment by Arcovv** [comment]
@GitZhouQi 
注意你的Xcode版本，Swift版本，可能要設定一下Carthage某些項目的版本號

**Comment by jv9** [comment]
Never mind. It's working now. Don't upgrade Alamofire to the latest. 
Run the following command after checking out the project:
**carthage bootstrap**
The **bootstrap** command will download and build the exact versions of your dependencies that are specified in Cartfile.resolved.
