### ISSUE TITLE
run on simulator

### ISSUE THREAD

**Issue by whqfor** [CatchChat/Yep#45]
sometimes i can run it, but sometimes  it will be crash 
<img width="848" alt="2016-02-04 11 06 01" src="https://cloud.githubusercontent.com/assets/12791878/12804612/9f9fb16e-cb2f-11e5-8feb-af628402306d.png">

**Comment by 03128crz** [comment]
I meeted the problem with you

**Comment by FengDeng** [comment]
up vote
8
down vote
accepted
	

I was able to solve this problem on my side. The documentation says

    Your app must have a com.apple.security.application-groups entitlement for the specified application group. <https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/index.html#//apple_ref/occ/instm/NSFileManager/containerURLForSecurityApplicationGroupIdentifier>

At some point in my app, I had removed the entitlements file from my app target/build settings/code signing/code signing entitlements . Both debug and release must include YOUR_APP.entitlements file . My debug wasn't including it so it wasn't working on simulator

**Comment by FengDeng** [comment]
I was able to solve this problem on my side. The documentation says
Your app must have a com.apple.security.application-groups entitlement for the specified application group. 
<https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/index.html#//apple_ref/occ/instm/NSFileManager/containerURLForSecurityApplicationGroupIdentifier>
At some point in my app, I had removed the entitlements file from my app target/build settings/code signing/code signing entitlements . Both debug and release must include YOUR_APP.entitlements file . My debug wasn't including it so it wasn't working on simulator

**Comment by ghostwolf90** [comment]
is this problem!?
https://github.com/CatchChat/Yep/issues/51

**Comment by qalandarov** [comment]
Select the Project -> Build Settings -> Search for STAGING_  and rename it to STAGING and run again
