### ISSUE TITLE
模拟器注册时输入手机号码后点下一步直接Crash

### ISSUE THREAD

**Issue by 03128crz** [CatchChat/Yep#47]
fatal error: unexpectedly found nil while unwrapping an Optional value

![snip20160204_47](https://cloud.githubusercontent.com/assets/3424553/12809857/3c82d16e-cb5d-11e5-932d-4878559cee6f.png)

**Comment by nixzhu** [comment]
baseURL is empty, try develop branch.

**Comment by LeeRHuang** [comment]
@nixzhu @kevinzhow @03128crz   when complie process a lots of problems,after solve these issues,i try to use my account to land,but i was stuck to jump to the next step，so i decided to register a new account,unlunckly,i got the crash upon floor had meet , can you give me some advice help?

**Comment by LeeRHuang** [comment]
i switch to develop branch,then i login successly.
