### ISSUE TITLE
Xcode 8 可以运行哪个分支？

### ISSUE THREAD

**Issue by Chen-Dixi** [CatchChat/Yep#481]
现在Yep有分支可以运行在Xcode 8上面吗，常识构建develop分支，提示User类有歧义。请问Yep是迁移到Swift2.3还是Swift 3

**Comment by nixzhu** [comment]
Yep 的日常开发在 develop 分支进行，代码已转换到 Swift 3.0。请确保 git pull 到最新代码，安装好所需的第三方库后再编译。
Chen-Dixi notifications@github.com于2016年10月3日 周一13:07写道：

**Comment by Chen-Dixi** [comment]
安装了CocoaPods,Carthage。 编译还是提示 'User' is ambiguous for type lookup in this context。请问，Yep是通过什么保存上次浏览的话题。 @nixzhu

**Comment by JessiePlus** [comment]
UserAvatar.swift:22:15: 'User' is ambiguous for type lookup in this context

**Comment by jv9** [comment]
@nixzhu 好像你没有commit你的code到develop branch。 我这里Develop的最后更新是 Sep 9th.
