### ISSUE TITLE
为什么dev分支缺少RealmSwift等Pod定义？

### ISSUE THREAD

**Issue by chinamcafee** [CatchChat/Yep#500]
拉取到最新的dev分支，发现原有的一些Pods依赖都删掉了，但是代码中明明还有依赖，比如RealmSwift，Alamofire等。如何再次通过编译？自行加入？

**Comment by jv9** [comment]
重新install就可以了。

**Comment by warmlight** [comment]
我也遇到同样的疑问,我是刚刚下的新项目，Kingfisher Realm等Pods的依赖都被删除了,但是代码里仍旧存在对这些库的依赖，请问如何正确编译？重新install具体是指什么呢？  @jv9

**Comment by warmlight** [comment]
我折腾了好久来run这个项目
之前所有的依赖都能用pod安装，现在缺少的pod依赖需要用carthage来安装，而项目里的carthage由于没有声明version，如果update会安装新的版本，这是最纠结的问题，要找到Yep使用的版本。下面是我最终跑通情况下cartfile的内容，希望有帮助（可能还有不对的地方，这个是我跑通的情况），少走那么多弯路。强烈建议在readme里加上一点install的步骤，可以节省很多的时间。
github "realm/realm-cocoa" ~> 0.100.0
github "onevcat/Kingfisher" ~> 2.1
github "tid-kijyun/Kanna" ~> 1.1.0
github "Alamofire/Alamofire" ~> 3.0
github "ReactiveX/RxSwift" ~> 2.0
github "nixzhu/Navi" ~> 0.4.0
github "nixzhu/KeyboardMan" ~> 0.6.0
github "nixzhu/Ruler" ~> 0.7.0
github "nixzhu/Proposer" ~> 0.8.0
github "nixzhu/MonkeyKing" ~> 0.0.2

**Comment by chinamcafee** [comment]
@warmlight 请问你这个配置是swift3.0跑通的，还是swift2.3？

**Comment by warmlight** [comment]
我没有切到develop上去跑，所以不是3.0的，我的xocde是7.3 @chinamcafee

**Comment by chinamcafee** [comment]
@warmlight 好的，我在用Xcode 8.0，按照你的思路我继续探索一下。多谢

**Comment by warmlight** [comment]
@chinamcafee  如果是3.0的话，这个文件其实不用怎么改，拉最新的反而是对的，这个时候要考虑的是否这些依赖都支持3.0，你可以尝试所有的依赖都用最新的跑跑看

**Comment by chinamcafee** [comment]
@warmlight 多谢，不过carthage在Downloading realm-cocoa.framework binary at "v1.1.0"这一步的时候，GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out."  这个您有遇到过吗？
