### ISSUE TITLE
您好，成功安裝到手機後，剛開始運行遇到這問題

### ISSUE THREAD

**Issue by ghostwolf90** [CatchChat/Yep#51]
您好
一開始 pod install後就能正常編譯完成
然後裝到iPhone後，遇到這狀況，請問是什麼問題呢?
![2016-02-05 13 29 14](https://cloud.githubusercontent.com/assets/6032046/12838749/af3a8814-cc0c-11e5-9141-c3f894e5740e.png)

**Comment by harrylin90** [comment]
添加一个All Exceptions断点进行调试。这是强制unwrap造成的。如以下代码：
let str: String! = nil
print(str)
这里是String!类型的，使用时必须判断是否为nil，为nil的代码不能进行。就会遇到fatal error: unexpectedly found nil while unwrapping an Optional value这样的问题。应该考虑使用String或者String?，比较安全。

**Comment by ghostwolf90** [comment]
謝謝，我試試!

**Comment by ghostwolf90** [comment]
後來發現是這一段問題
在func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) 裡第一段
Realm.Configuration.defaultConfiguration = realmConfig()
![2016-02-05 15 14 04](https://cloud.githubusercontent.com/assets/6032046/12840138/6264683e-cc1b-11e5-822d-44a41054e7b8.png)
![2016-02-05 15 14 34](https://cloud.githubusercontent.com/assets/6032046/12840141/68a76354-cc1b-11e5-905c-ef1dd37c5ebc.png)
似乎是設定App Group的問題
 
不過不過增加上自己的Bundle identifier後，問題還是跟上面一樣 囧

**Comment by harrylin90** [comment]
看一下realmConfig()方法，是不是let directory: NSURL = NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier(YepConfig.appGroupID)!
        let realmPath = directory.URLByAppendingPathComponent("db.realm").path!出现了nil值？

**Comment by ghostwolf90** [comment]
謝謝你!

**Comment by ghostwolf90** [comment]
找到問題了，原來是appGroupID要改為自己的
static let appGroupID: String = "group.com.LaiBit.Yep"

**Comment by harrylin90** [comment]
@ghostwolf90 you're welcome
