### ISSUE TITLE
error about optional value(NSIndexPath) in file:ConversationLayout.swift

### ISSUE THREAD

**Issue by YuheCui** [CatchChat/Yep#52]
File location: Yep -> viewControllers -> conversation -> conversationLayout.swift
Row 30 of ConversationLayout.swift:
```
if let indexPath = updateItem.indexPathAfterUpdate
```
error description: Initializer for conditional binding must have Optional type, not 'NSIndexPath'.
Below is the detail, tks.

[
![2016-02-09 3 35 01](https://cloud.githubusercontent.com/assets/14869903/12910166/e8b6e2e8-cf42-11e5-84de-65ef5b01764b.png)
](url)

**Comment by zenghaojim33** [comment]
+1

**Comment by kevinzhow** [comment]
Latest version should fixed this
