### ISSUE TITLE
Installing Realm failed

### ISSUE THREAD

**Issue by LeeRHuang** [CatchChat/Yep#55]
When i have cloned the repository,it remind me that i need update my cocoapods,so i open my terminal,execute pod update ,everything goes normal,but when installing Realm,fall failed,tips is
 “[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.96.1
Downloading core failed:
curl: (56) SSLRead() return error -9806”
As the post https://github.com/realm/realm-cocoa/issues/2713 describe,it due to china mainland GFW,so i tried VPN and prebulid version,but unfortunate,it take no effect.

**Comment by Yoncise** [comment]
You can follow the steps I replied to you in #3183 :)

**Comment by LeeRHuang** [comment]
Thanks  Yoncise  :)
