### ISSUE TITLE
develop branch跟新代码到Merge branch 'feature/avatar_performance' into develop

### ISSUE THREAD

**Issue by lacusrinz** [CatchChat/Yep#56]
运行程序，登陆APP后界面无响应，真机模拟器一样，程序没有异常，没有报错，点击任何按钮无响应，界面上也没有跟新出任何消息，revert代码回上个版本后一切正常

Xcode7.2.1 iPhone6

**Comment by LeeRHuang** [comment]
楼主解决了？原因是缺少baseUrl
