### ISSUE TITLE
Unable to find a specification for `FayeClient`

### ISSUE THREAD

**Issue by CaliosD** [CatchChat/Yep#593]
Hi, I'm sorry to trouble, but I need your help. 
But after cloning the develop branch and trying `pod install`, I've got an error named `Unable to find a specification for FayeClient`. I tried to find one with the same name, and only got this(https://cocoapods.org/pods/FayeClient). Updated the line in  podfile to  `pod 'FayeClient', '~> 1.0.0'`, I still get the same error. 
Could you please help me with this issue? Thanks so much in advance.

**Comment by nixzhu** [comment]
You may need `pod repo update` before `pod install`.
CocoaPods(after 1.0.0) will not update repo spec, so you need to do it yourself.

**Comment by CaliosD** [comment]
Fantastic! It works. Thanks... and happy late Thanksgiving Day ! :P
