### ISSUE TITLE
运行时报错，求解决

### ISSUE THREAD

**Issue by IDEAL-YANG** [CatchChat/Yep#60]
1.-weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
2.error: cannot parse the debug map for "/Users/apple/Library/Developer/Xcode/DerivedData/Yep-gouotshhrmygmlfbwvfancwfrsyn/Build/Products/Debug-iphoneos/Yep.app/Yep": No such file or directory

**Comment by kevinzhow** [comment]
Use develop branch
