### ISSUE TITLE
无法登录和注册

### ISSUE THREAD

**Issue by yangxiaobo** [CatchChat/Yep#654]
登录报错：
***************************** YepNetworking Failure *****************************
Reason: Other, Error: Optional(Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={NSUnderlyingError=0x170459110 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://api.soyep.com/v1/sms_verification_codes, NSErrorFailingURLKey=https://api.soyep.com/v1/sms_verification_codes, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=请求超时。})
Resource(Method: POST, path: /v1/sms_verification_codes, headers: ["Content-Type": "application/json", "Accept-Language": "zh-CN"], requestBody: ["mobile": 18611015754, "method": sms, "phone_code": 86])

**Comment by Shunzi007** [comment]
@yangxiaobo Yep的后台好像是停了

**Comment by itjhDev** [comment]
应该是下架了, 官网都访问不了

**Comment by Huang-Libo** [comment]
怎么就下架了呢, nixZhu 也消失了
