### ISSUE TITLE
你好，注册的时候出现问题

### ISSUE THREAD

**Issue by ganjmeng** [CatchChat/Yep#71]
![ac6cab70-3324-4eef-b042-62d121c0b864](https://cloud.githubusercontent.com/assets/12026835/13842369/bb90a216-ec68-11e5-8dc4-575d6c402ef4.png)
求解决，感觉这个项目很炫啊

**Comment by gechanghang** [comment]
在Other Swift Flags中修改条件编译

**Comment by 520xiaopohai** [comment]
改成什么呢  同求

**Comment by gechanghang** [comment]
把STAGING_ 最后面的下划线去掉就可以了
