### ISSUE TITLE
你好我在AppStore上下载的版本也是，好像是服务挂了，楼主看看啊。。。

### ISSUE THREAD

**Issue by ganjmeng** [CatchChat/Yep#72]
你好我在AppStore上下载的版本也是，好像是服务挂了，楼主看看啊。。。

**Comment by xuyouhong** [comment]
搜嘎    我是用github源码跑的，楼主已经不知道哪里去了，都好久了，我一周之前就注册失败了

**Comment by kevinzhow** [comment]
@ganjmeng 现在呢？

**Comment by ganjmeng** [comment]
@kevinzhow 还是不行，没法注册
