### ISSUE TITLE
Pods folder missing 

### ISSUE THREAD

**Issue by wellkunnected** [CatchChat/Yep#73]
I am trying to build this app and the folder that should be including labeled "pods" is missing. When opening this project in Xcode the pods file is in red letting me know the pods folder for the dependencies are missing. A lot of developers on github don't include the pods folder with the project assuming everyone trying out the code will be able to install the pods dependacies without it but that's not the case. I can never get an app to work that uses cocoapods that doesn't include the pods folders. Can you help me out and add the pods folder to project please? I am very interested to test out this project. Thanks for your help.

**Comment by kevinzhow** [comment]
Use Develop branch

**Comment by wellkunnected** [comment]
I am a beginner developer so I am familiar with all functions. How would I use "develop branch"? Thank you for your kind help sir.

**Comment by wellkunnected** [comment]
I found the Develop Branch and downloaded that file but it still tells me the pods folder is missing. Anyway you can simply email it to me to avoid all the confusion? I am not good with installing cocoapods without the required pods folder.

**Comment by wellkunnected** [comment]
Figured it out watching a tutorial on Youtube, thanks for your help and
I'll report back with any new findings on the app!

On Tue, Mar 29, 2016 at 1:21 AM, Kevin <notifications@github.com> wrote:

> Use Develop branch
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CatchChat/Yep/issues/73#issuecomment-202715572>
>



-- 




Founded Well Kunnected, Inc 2010
