### ISSUE TITLE
证书原因无法真机调试

### ISSUE THREAD

**Issue by geekAK** [CatchChat/Yep#8]

**Comment by geekAK** [comment]
本地该做何配置，才能免证书真机运行？

**Comment by kevinzhow** [comment]
选择 None

**Comment by lacusrinz** [comment]
dev branch 选none，没效果
![2016-02-13 8 15 18](https://cloud.githubusercontent.com/assets/5283022/13027559/95ffae6e-d28e-11e5-888f-5b44e64e1fb7.png)
