### ISSUE TITLE
模拟机 crash 

### ISSUE THREAD

**Issue by leibaozai** [CatchChat/Yep#93]
显示这个错误--->       fatal error: unexpectedly found nil while unwrapping an Optional value
![1](https://cloud.githubusercontent.com/assets/12133314/14198163/93bfd87c-f809-11e5-81b5-900f49d66c46.png)

**Comment by zenghaojim33** [comment]
+1

**Comment by sd2562991** [comment]
+1

**Comment by Sexyrabbit** [comment]
楼上+1
